active_monitors: 11,12,21,22,31,32,41,42,51,52,61,62,71,72,81,82

device_info: 
    device_type: cisco_ios
    ip: 10.m.m.1
    port: 22
    username: admin
    password: pass
    secret: pass

ips: 
    password: pass
    no_timeout: 0 0
    gi0/0/1: '200.0.0'
    lo0: '0.0.1'
    mask_16: '255.255.0.0'
    mask_24: '255.255.255.0'
    mask_32: '255.255.255.255'
    wild_24: '0.0.0.255'
    wild_32: '0.0.0.0'
    via_py: -configured-via-python

ospf:
    process: '1'
    area: 'area 0'